
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: mess_dev

test:
  <<: *default
  database: mess_test
